import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs'
const b = await chromium.launch({ args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'] })
const pg = await b.newPage({ viewport: { width: 480, height: 360 } })
pg.on('console', m => { if (m.type()==='error') console.log('ERR', m.text()) })
await pg.goto('http://127.0.0.1:5173/')
await pg.waitForSelector('button.choose', { timeout: 60000 })
const f0 = await pg.evaluate(async () => { const a = window.__frames; await new Promise(r=>setTimeout(r,3000)); return (window.__frames-a)/3 })
console.log('board fps', f0)
await pg.locator('button.choose').first().click({ timeout: 60000 })
await pg.waitForTimeout(4000)
await pg.locator('#play').click({ timeout: 60000 })
await pg.waitForTimeout(4000)
const fps = await pg.evaluate(async () => { const a = window.__frames; await new Promise(r=>setTimeout(r,3000)); return (window.__frames-a)/3 })
console.log('arena fps', fps)
await pg.screenshot({ path: 'arena.png', timeout: 120000 })
await b.close()
