import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs'
const b = await chromium.launch({ args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'] })
const pg = await b.newPage({ viewport: { width: 520, height: 420 } })
pg.on('pageerror', e => console.log('PAGEERR', e.message))
await pg.goto('http://127.0.0.1:5173/')
await pg.waitForSelector('button.choose', { timeout: 90000 })
await pg.locator('button.choose').nth(3).click({ timeout: 60000 })
await pg.waitForTimeout(3000)
await pg.locator('#play').click({ timeout: 60000 })
await pg.waitForTimeout(5000)
await pg.addStyleTag({ content: '#legend,#hud{display:none!important}' })
const game = async (s) => pg.evaluate(async (s) => { const f = window.__fighter; const t0 = f.time; await new Promise(r => { const tick = () => { if (f.time - t0 >= s) r(); else requestAnimationFrame(tick) }; tick() }) }, s)
const freeze = () => pg.evaluate(() => { window.__fighter.speed = 0.005 })
const go = () => pg.evaluate(() => { window.__fighter.speed = 1 })
const reset = async (x) => { for (const k of ['d','Shift']) await pg.keyboard.up(k); await pg.evaluate((x) => { const f = window.__fighter; f.pos.set(x, 0, 0); f.vel.set(0,0,0) }, x) }
const shot = async (n) => { console.log(n, await pg.evaluate(() => window.__fighter.current)); await pg.screenshot({ path: n, timeout: 120000 }) }
await pg.evaluate(() => { window.__turntable.pitch = -0.35 })
await reset(-3); await game(0.6)
await pg.keyboard.down('d')
await game(0.9); await freeze(); await shot('p_run.png'); await go()
await reset(-5); await game(0.4)
await pg.keyboard.down('Shift'); await pg.keyboard.down('d')
await game(1.1); await freeze(); await shot('p_sprint.png'); await go()
await reset(0); await game(0.8)
await pg.keyboard.down(' ')
await game(0.3); await freeze(); await shot('p_apex.png'); await go(); await game(0.22); await freeze(); await shot('p_land.png'); await go(); await pg.keyboard.up(' ')
await b.close()
