import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs'
const b = await chromium.launch({ args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'] })
const pg = await b.newPage({ viewport: { width: 560, height: 460 } })
pg.on('pageerror', e => console.log('PAGEERR', e.message))
await pg.goto('http://127.0.0.1:5173/')
await pg.waitForSelector('button.choose', { timeout: 90000 })
await pg.locator('button.choose').nth(3).click({ timeout: 60000 })
await pg.waitForTimeout(3000)
await pg.locator('#play').click({ timeout: 60000 })
await pg.waitForTimeout(5000)
await pg.addStyleTag({ content: '#legend,#hud{display:none!important}' })
// Temps de jeu mesuré, pas le temps réel : on attend N secondes *de jeu*.
const game = async (secs) => pg.evaluate(async (s) => { const f = window.__fighter; let t = 0; const t0 = f.time; await new Promise(r => { const tick = () => { if (f.time - t0 >= s) r(); else requestAnimationFrame(tick) }; tick() }) }, secs)
const shot = async (name) => pg.screenshot({ path: name, timeout: 120000 })
// vue de profil : la caméra à 90°
await pg.evaluate(() => { window.__turntable.yaw = Math.PI / 2 })
await game(1)
await pg.evaluate(() => { const f = window.__fighter; f.input.y = 1 })  // course vers le haut de l'écran
await game(1.2)
await pg.evaluate(() => { window.__fighter.speed = 0.02 })
await shot('k_run.png')
await pg.evaluate(() => { const f = window.__fighter; f.speed = 1; f.sprint = true })
await game(1.2)
await pg.evaluate(() => { window.__fighter.speed = 0.02 })
await shot('k_sprint.png')
await pg.evaluate(() => { const f = window.__fighter; f.speed = 1; f.sprint = false; f.input.y = 0 })
await game(1.2)
await pg.evaluate(() => { const f = window.__fighter; f.press('jump') })
await game(0.14)
await pg.evaluate(() => { window.__fighter.speed = 0.02 })
await shot('k_jump_up.png')
await pg.evaluate(() => { const f = window.__fighter; f.speed = 1 })
await game(1.2)
await pg.evaluate(() => { window.__turntable.yaw = 0; })
await game(0.5)
await pg.evaluate(() => { const f = window.__fighter; f.input.x = 1; f.press('dodge'); f.input.x = 0 })
await game(0.08)
await pg.evaluate(() => { window.__fighter.speed = 0.02 })
await shot('k_dodge.png')
await pg.evaluate(() => { const f = window.__fighter; f.speed = 1 })
await game(1)
await pg.evaluate(() => { const f = window.__fighter; f.press('attack') })
await game(0.2)
await pg.evaluate(() => { window.__fighter.speed = 0.02 })
await shot('k_attack.png')
await b.close()
