import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs'
const b = await chromium.launch({ args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'] })
const pg = await b.newPage({ viewport: { width: 520, height: 400 } })
pg.on('console', m => { if (m.type()==='error' || m.type()==='warning') console.log(m.type(), m.text().slice(0,300)) })
pg.on('pageerror', e => console.log('PAGEERR', e.message))
await pg.goto('http://127.0.0.1:5173/')
await pg.waitForSelector('button.choose', { timeout: 90000 })
await pg.locator('button.choose').nth(1).click({ timeout: 60000 })
await pg.waitForTimeout(3000)
await pg.locator('#play').click({ timeout: 60000 })
await pg.waitForTimeout(6000)
const st = await pg.evaluate(() => ({ err: window.__err, cap: window.__cap, cur: window.__fighter?.current }))
console.log(JSON.stringify(st))
await pg.screenshot({ path: 'arena_idle.png', timeout: 120000 })
// accroupi : pose figée via ralenti
await pg.evaluate(() => { const f = window.__fighter; f.speed = 0.15; f.press('jump') })
await pg.waitForTimeout(2500)
await pg.screenshot({ path: 'arena_jump.png', timeout: 120000 })
await pg.evaluate(() => { const f = window.__fighter; f.speed = 1; f.input.x = 1; f.sprint = true })
await pg.waitForTimeout(1500)
await pg.evaluate(() => { const f = window.__fighter; f.speed = 0.1 })
await pg.screenshot({ path: 'arena_sprint.png', timeout: 120000 })
console.log(await pg.evaluate(() => window.__fighter.current))
await b.close()
