import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs'
const b = await chromium.launch({ args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'] })
const pg = await b.newPage({ viewport: { width: 520, height: 440 } })
pg.on('pageerror', e => console.log('PAGEERR', e.message))
await pg.goto('http://127.0.0.1:5173/')
await pg.waitForSelector('button.choose', { timeout: 90000 })
const names = await pg.$$eval('.label .name', els => els.map(e => e.textContent))
console.log(names)
const game = async (s) => pg.evaluate(async (s) => { const f = window.__fighter; const t0 = f.time; await new Promise(r => { const tick = () => { if (f.time - t0 >= s) r(); else requestAnimationFrame(tick) }; tick() }) }, s)
const freeze = () => pg.evaluate(() => { window.__fighter.speed = 0.005 })
const go = () => pg.evaluate(() => { window.__fighter.speed = 1 })
for (const want of ['ÉCHARPE', 'COLLIER']) {
  const i = names.indexOf(want)
  await pg.locator('button.choose').nth(i).click({ timeout: 60000 })
  await pg.waitForTimeout(2500)
  await pg.locator('#play').click({ timeout: 60000 })
  await pg.waitForTimeout(4000)
  await pg.addStyleTag({ content: '#legend,#hud{display:none!important}' })
  await pg.evaluate(() => { window.__turntable.yaw = 2.4 })
  await game(1.5); await freeze()
  await pg.screenshot({ path: `s_${want}_idle.png`, timeout: 120000 }); await go()
  await pg.keyboard.press('j'); await game(0.2); await freeze()
  await pg.screenshot({ path: `s_${want}_hit.png`, timeout: 120000 }); await go()
  await pg.keyboard.down('Shift'); await pg.keyboard.down('d'); await game(1.0); await freeze()
  await pg.screenshot({ path: `s_${want}_run.png`, timeout: 120000 }); await go()
  await pg.keyboard.up('d'); await pg.keyboard.up('Shift')
  console.log(want, await pg.evaluate(() => [window.__err?.message, window.__cap]))
  await pg.keyboard.press('Escape'); await pg.waitForTimeout(500); await pg.keyboard.press('Escape'); await pg.waitForTimeout(3000)
}
await b.close()
