import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs'
const b = await chromium.launch({ args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'] })
const pg = await b.newPage({ viewport: { width: 520, height: 420 } })
pg.on('pageerror', e => console.log('PAGEERR', e.message))
pg.on('console', m => { if (m.type() === 'error') console.log('ERR', m.text().slice(0, 300)) })
await pg.goto('http://127.0.0.1:5173/')
await pg.waitForSelector('button.choose', { timeout: 90000 })
await pg.evaluate(() => document.querySelectorAll('button.choose')[2].click())
await pg.waitForTimeout(2500)
await pg.waitForSelector('#play', { timeout: 90000 }); await pg.evaluate(() => document.querySelector('#play').click())
await pg.waitForTimeout(4000)
await pg.addStyleTag({ content: '#legend,#hud{display:none!important}' })
const game = async (s) => pg.evaluate(async (s) => { const f = window.__fighter; const t0 = f.time; await new Promise(r => { const tick = () => { if (f.time - t0 >= s) r(); else requestAnimationFrame(tick) }; tick() }) }, s)
const freeze = () => pg.evaluate(() => { window.__fighter.speed = 0.004 })
const go = () => pg.evaluate(() => { window.__fighter.speed = 1 })
await game(0.8)
// dash à droite
await pg.keyboard.down('d'); await pg.keyboard.press('l'); await game(0.11); await freeze()
await pg.screenshot({ path: 'g_dash.png', timeout: 120000 }); await go(); await pg.keyboard.up('d')
await game(0.8)
// glissade vers la gauche, tenue
await pg.evaluate(() => { const f = window.__fighter; f.pos.set(4, 0, 0) })
await pg.keyboard.down('q'); await pg.keyboard.down('l'); await game(0.9); await freeze()
await pg.screenshot({ path: 'g_glide.png', timeout: 120000 }); await go()
console.log(await pg.evaluate(() => [window.__fighter.gliding, window.__fighter.current, window.__gl.info.render.calls]))
await pg.keyboard.up('l'); await pg.keyboard.up('q')
await b.close()
