import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs'
const b = await chromium.launch({ args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'] })
const pg = await b.newPage({ viewport: { width: 520, height: 420 } })
pg.on('pageerror', e => console.log('PAGEERR', e.message))
await pg.goto('http://127.0.0.1:5173/')
await pg.waitForSelector('button.choose', { timeout: 90000 })
await pg.locator('button.choose').nth(0).click({ timeout: 60000 })
await pg.waitForTimeout(3000)
await pg.locator('#play').click({ timeout: 60000 })
await pg.waitForTimeout(5000)
await pg.addStyleTag({ content: '#legend,#hud{display:none!important}' })
const game = async (s) => pg.evaluate(async (s) => { const f = window.__fighter; const t0 = f.time; await new Promise(r => { const tick = () => { if (f.time - t0 >= s) r(); else requestAnimationFrame(tick) }; tick() }) }, s)
const freeze = () => pg.evaluate(() => { window.__fighter.speed = 0.005 })
const go = () => pg.evaluate(() => { window.__fighter.speed = 1 })
const shot = async (n) => { console.log(n, await pg.evaluate(() => [window.__fighter.current, window.__err, window.__cap])); await pg.screenshot({ path: n, timeout: 120000 }) }
await pg.evaluate(() => { window.__turntable.yaw = 0.5 })
await game(0.8)
await pg.keyboard.press('k'); await game(0.2); await freeze(); await shot('c_parry.png'); await go()
await game(0.8)
await pg.keyboard.press('x'); await game(0.62); await freeze(); await shot('c_ko_fall.png'); await go()
await game(1.2); await freeze(); await shot('c_ko_rest.png'); await go()
await pg.keyboard.press('x'); await game(0.5); await freeze(); await shot('c_rise.png'); await go()
await b.close()
