import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs'
const b = await chromium.launch({ args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'] })
const pg = await b.newPage({ viewport: { width: 480, height: 420 } })
pg.on('pageerror', e => console.log('PAGEERR', e.message))
await pg.goto('http://127.0.0.1:5173/')
await pg.waitForSelector('button.choose', { timeout: 120000 })
await pg.evaluate(() => document.querySelectorAll('button.choose')[4].click())
await pg.waitForSelector('#play', { timeout: 90000 }); await pg.evaluate(() => document.querySelector('#play').click())
await pg.waitForTimeout(4000)
await pg.addStyleTag({ content: '#legend,#hud{display:none!important}' })
const game = async (s) => pg.evaluate(async (s) => { const f = window.__fighter; const t0 = f.time; await new Promise(r => { const tick = () => { if (f.time - t0 >= s) r(); else requestAnimationFrame(tick) }; tick() }) }, s)
const freeze = () => pg.evaluate(() => { window.__fighter.speed = 0.004 })
const go = () => pg.evaluate(() => { window.__fighter.speed = 1 })
await game(0.5)
await pg.keyboard.down(' '); await game(0.1); await pg.keyboard.up(' ')
await game(0.25)
await pg.keyboard.down(' '); await game(0.12); await freeze()
await pg.screenshot({ path: 'sig_dj.png', timeout: 180000 }); await go(); await pg.keyboard.up(' ')
await game(1.5)
await pg.evaluate(() => { window.__fighter.pos.set(-7, 0, 0) })
await pg.keyboard.down('Shift'); await pg.keyboard.down('d'); await game(0.8)
await pg.keyboard.down('l'); await game(0.6)
await pg.keyboard.up('d'); await pg.keyboard.down('z'); await game(0.35); await freeze()
console.log(await pg.evaluate(() => [window.__fighter.gliding, Math.hypot(window.__fighter.vel.x, window.__fighter.vel.z).toFixed(1)]))
await pg.screenshot({ path: 'sig_glide.png', timeout: 180000 })
await b.close()
